# GenerateVersion.cmake — run at build time to embed git hash into Version.h
# Called via add_custom_target with cmake -P

# Read the base version from the cache
set(VERSION_MAJOR "${VERSION_MAJOR}")
set(VERSION_MINOR "${VERSION_MINOR}")
set(VERSION_PATCH "${VERSION_PATCH}")

# Get short git commit hash
execute_process(
    COMMAND git rev-parse --short HEAD
    WORKING_DIRECTORY "${SOURCE_DIR}"
    OUTPUT_VARIABLE GIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE GIT_RESULT
)

if(NOT GIT_RESULT EQUAL 0)
    set(GIT_HASH "unknown")
endif()

# Check for uncommitted changes
execute_process(
    COMMAND git status --porcelain
    WORKING_DIRECTORY "${SOURCE_DIR}"
    OUTPUT_VARIABLE GIT_STATUS
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
)

set(GIT_DIRTY "")
if(NOT "${GIT_STATUS}" STREQUAL "")
    set(GIT_DIRTY "-dirty")
endif()

set(VERSION_STRING "${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}+${GIT_HASH}${GIT_DIRTY}")

# Only write if content changed (avoid unnecessary rebuilds)
set(NEW_CONTENT "#pragma once
// Auto-generated by CMake — do not edit
#define YAWN_VERSION_MAJOR ${VERSION_MAJOR}
#define YAWN_VERSION_MINOR ${VERSION_MINOR}
#define YAWN_VERSION_PATCH ${VERSION_PATCH}
#define YAWN_GIT_HASH \"${GIT_HASH}${GIT_DIRTY}\"
#define YAWN_VERSION_STRING \"${VERSION_STRING}\"
")

set(OUTPUT_FILE "${OUTPUT_DIR}/Version.h")

if(EXISTS "${OUTPUT_FILE}")
    file(READ "${OUTPUT_FILE}" OLD_CONTENT)
    if("${OLD_CONTENT}" STREQUAL "${NEW_CONTENT}")
        return()
    endif()
endif()

file(WRITE "${OUTPUT_FILE}" "${NEW_CONTENT}")
message(STATUS "Generated Version.h: ${VERSION_STRING}")
